version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9.6  # e.g., 3.8
    commands:
      - pip install -r requirements.txt  # This command will use setup.py to install dependencies

  build:
    commands:
      - echo "Starting the build process"
      
  post_build:
    commands:
      - echo "Build process complete"

artifacts:
  files:
    - '**/*'  # Includes all files for deployment
  discard-paths: yes
