# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformancepredict

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://studentperformancepredict.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5c7a9f4e1cb8471aa69e8c31bb678d82 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_be4ee9ea24a84d158e7e938aa799d868 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: studentperformancepredict.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5c7a9f4e1cb8471aa69e8c31bb678d82 }}/student-performance-predict:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformancepredict'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_004ff0620e574a66899e6e74f802afa9 }}
        images: 'studentperformancepredict.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5c7a9f4e1cb8471aa69e8c31bb678d82 }}/student-performance-predict:${{ github.sha }}'